DROP TABLE IF EXISTS url;
DROP TABLE IF EXISTS video;

CREATE TABLE url (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  prog_url TEXT NOT NULL,
  status TEXT NOT NULL,
  prog_id TEXT UNIQUE,
  FOREIGN KEY (prog_id) REFERENCES video (id)
);

CREATE TABLE video (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  prog_id TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  filename TEXT NOT NULL,
  metajson TEXT NOT NULL
);
