swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /video:
    get:
      operationId: flaskr.video.read_all
      tags:
        - Video
      summary: Read list of video
      description: return list of all video   
      responses:
        200:
          description: Successfully read video list
          schema:
            type: array
            items:
              properties:
                url:
                  type: string
                status:
                  type: string
                timestamp:
                  type: string
                mdata:
                  type: string

    post:
      operationId: flaskr.video.addurl
      tags:
        - Video
      summary: Add a video
      description: Add the video with the given url
      parameters:
        - name: url
          in: query
          description: url of the video to add
          required: True
          type: string

      responses:
        201:
          description: Successfully downlaoded video

  /video/{video_id}:
    get:
      operationId: flaskr.video.read_one
      tags:
        - Video
      summary: Read one video info
      description: return one video info   
      parameters:
        - name: video_id
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully read one video data
          schema:
            properties:
              url:
                type: string
              status:
                type: string
              timestamp:
                type: string
              mdata:
                type: string

    delete:
      operationId: flaskr.video.delete
      tags:
        - Video
      summary: Delete a video from db
      description: Delete a video
      parameters:
        - name: video_id
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted a video from db

  /download/{video_id}:
    get:
      operationId: flaskr.video.download
      tags:
        - Video
      summary: Download a video from db
      description: Download a video
      parameters:
        - name: video_id
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully start download a video

    delete:
      operationId: flaskr.video.cancel
      tags:
        - Video
      summary: Cancel a video download
      description: Cancel a video download
      parameters:
        - name: video_id
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully cancel a video download

  /status/{video_id}:
    get:
      operationId: flaskr.video.get_status
      tags:
        - Video
      summary: Get a video download status
      description: Get a video download status
      parameters:
        - name: video_id
          in: path
          type: string
          required: True
      responses:
        200:
          description: download progress status
          schema:
            properties:
              video_id:
                type: string
              status:
                type: string
              progress:
                type: string
          